name: Run Cypress Test Manually

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Chemin vers le fichier de test Cypress à exécuter'
        required: true
        default: 'cypress/e2e/login.cy.js'

jobs:
  run-specific-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./front

      - name: Run specific Cypress test
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./front
          record: true
          key: ${{ secrets.CYPRESS_RECORD_KEY }}
          spec: ${{ github.event.inputs.test_file }}
